
CREATE TABLE IF NOT EXISTS AUTHOR
(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
SURNAME VARCHAR(255) NOT NULL,
DATE_OF_BIRTH VARCHAR(255) NOT NULL,
SEX VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK
(
ID INT AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(255) NOT NULL,
YEAR_OF_PUBLICATION VARCHAR(255) NOT NULL,
AUTHOR_ID INT,
PUBLISHER VARCHAR(255),
FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR (ID)
);

INSERT INTO AUTHOR VALUES (1, 'Pushkin', 'Alex', '1799', 'm');
INSERT INTO BOOK VALUES (1, 'Rybka', '1825', 1, 'Moscow')