CREATE TABLE IF NOT EXISTS AUTHOR
(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
SURNAME VARCHAR(255) NOT NULL,
DATE_OF_BIRTH VARCHAR(255) NOT NULL,
GENDER VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK
(
ID INT AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(255) NOT NULL,
YEAR_OF_PUBLICATION VARCHAR(255) NOT NULL,
PUBLISHER VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK_AUTHOR
(
ID INT AUTO_INCREMENT PRIMARY KEY,
BOOK_ID INT NOT NULL,
AUTHOR_ID INT NOT NULL,
FOREIGN KEY(BOOK_ID) REFERENCES BOOK (ID),
FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR (ID)
);

INSERT INTO AUTHOR VALUES (1, 'Terry', 'Pratchett', '28.04.1948', 'male');
INSERT INTO AUTHOR VALUES (2, 'Neil', 'Gaiman', '10.11.1960', 'male');
INSERT INTO AUTHOR VALUES (3, 'George', 'Orwell', '25.06.1903', 'male');
INSERT INTO BOOK VALUES (1, 'Good omens', '2019', 'Eksmo');
INSERT INTO BOOK VALUES (2, '1984', '2013', 'AST');
INSERT INTO BOOK_AUTHOR VALUES (1, 1, 1);
INSERT INTO BOOK_AUTHOR VALUES (2, 1, 2);
INSERT INTO BOOK_AUTHOR VALUES (3, 2, 3);