
CREATE TABLE IF NOT EXISTS AUTHOR
(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
SURNAME VARCHAR(255) NOT NULL,
DATE_OF_BIRTH VARCHAR(255) NOT NULL,
GENDER VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK
(
ID INT AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(255) NOT NULL,
YEAR_OF_PUBLICATION VARCHAR(255) NOT NULL,
PUBLISHER VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK_AUTHOR
(
ID INT AUTO_INCREMENT PRIMARY KEY,
BOOK_ID INT ,
AUTHOR_ID INT NOT NULL,
FOREIGN KEY(BOOK_ID) REFERENCES BOOK (ID),
FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR (ID)
);

INSERT INTO AUTHOR VALUES (1, 'Ilya', 'Ilf', '06.12.1799', 'male');
INSERT INTO AUTHOR VALUES (2, 'Alexander', 'Petrov', '06.11.1799', 'male');
INSERT INTO AUTHOR VALUES (3, 'Leo', 'Tolstoy', '15.08.1899', 'male');
INSERT INTO BOOK VALUES (1, 'Rybka', '1825', 'Moscow');
INSERT INTO BOOK VALUES (2, 'Koshka', '1555', 'Peterburg');
INSERT INTO BOOK_AUTHOR VALUES (1, 1, 1);
INSERT INTO BOOK_AUTHOR VALUES (2, 1, 2);
INSERT INTO BOOK_AUTHOR VALUES (3, 2, 3);